9:11 - 11:19 yxy
azlhiacneg/veritasium-translate pull request #71
Opened 2021-12-04 19:54 UTC by yxyyeah

2021-12-07 14:52 UTC, ous50 requested changes

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
>  Dialogue: 0,0:09:07.05,0:09:10.45,Chinese,,0,0,0,,整个过程会经过大约 30 到 45 分钟
Dialogue: 0,0:09:07.05,0:09:10.45,Chinese,,0,0,0,,整个过程历时大约 30 到 45 分钟

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:09:11.93,0:09:14.17,Chinese,,0,0,0,,20世纪30年代，正在日本北海道大学
在20世纪30年代，中谷宇吉郎教授在日本北海道大学

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:09:14.17,0:09:16.27,Chinese,,0,0,0,,对雪花进行系统性研究的
对雪花进行了系统性的研究

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:09:18.91,0:09:21.79,Chinese,,0,0,0,,不同种类的雪花
他发现不同种类的雪花

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:09:33.40,0:09:37.46,Chinese,,0,0,0,,把他的发现汇总之后 就是这张 中谷图表
他的发现被总结成了中谷图表

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:09:40.07,0:09:43.39,Chinese,,0,0,0,,在零下2摄氏度左右，形成片状雪花
在零下2摄氏度左右，你将获得片状雪花

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:10:07.90,0:10:10.27,Chinese,,0,0,0,,嗯，当然，某种程度上是的
对，当然，某种程度上是这样的

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:10:12.11,0:10:13.94,Chinese,,0,0,0,,啊 我多多少少能说出来这个雪花晶体是在什么条件下形成的
如果您要合并多行翻译，请把这一句去掉并在最后的一句中文翻译的时间戳修改成整段翻译的起始时间

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:10:13.94,0:10:16.56,Chinese,,0,0,0,,啊 我多多少少能说出来这个雪花晶体是在什么条件下形成的
Dialogue: 0,0:10:12.11,0:10:16.56,Chinese,,0,0,0,,啊 我多多少少能说出来这个雪花晶体是在什么条件下形成的

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:10:13.94,0:10:16.56,Chinese,,0,0,0,,啊 我多多少少能说出来这个雪花晶体是在什么条件下形成的
像这样

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:10:51.28,0:10:56.30,Chinese,,0,0,0,,而是因为它们两头所处的环境完全一致
Dialogue: 0,0:10:51.28,0:10:56.30,Chinese,,0,0,0,,而是因为它们两边所处的环境完全一致

2021-12-07 14:52 UTC, ous50 commented on snowflakes/snowflakes.ass
>  Dialogue: 0,0:10:59.30,0:11:00.83,English,,0,0,0,,the temperature will change, say,
Dialogue: 0,0:10:59.30,0:11:00.83,English,,0,0,0,,the temperature will change

2021-12-11 05:08 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:09:43.39,0:09:47.26,Chinese,,0,0,0,,零下5摄氏度时，形成柱状和针状雪花
```suggestion
Dialogue: 0,0:09:43.39,0:09:47.26,Chinese,,0,0,0,,零下5摄氏度时  形成柱状和针状雪花

```

2021-12-11 05:08 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:09:47.26,0:09:50.44,Chinese,,0,0,0,,到零下15摄氏度，又变回片状雪花了
```suggestion
Dialogue: 0,0:09:47.26,0:09:50.44,Chinese,,0,0,0,,到零下15摄氏度  又变回片状雪花了

```

2021-12-11 05:08 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:09:50.44,0:09:54.69,Chinese,,0,0,0,,温度低于零下20度之后，又将会是柱状和片状雪花
```suggestion
Dialogue: 0,0:09:50.44,0:09:54.69,Chinese,,0,0,0,,温度低于零下20度之后  则是柱状和片状雪花

```

2021-12-11 05:09 UTC, merged