Update snowflakes.ass
azlhiacneg/veritasium-translate pull request #72
Opened 2021-12-05 08:11 UTC by shiyou1123

0:00~2:49 碧凌

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 requested changes

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:47.07,0:00:50.26,Chinese,,0,0,0,,直到一本也卖不出去
```suggestion
Dialogue: 0,0:00:47.07,0:00:51.26,Chinese,,0,0,0,,直到最后一本都卖不出去

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:50.26,0:00:51.26,Chinese,,0,0,0,,我们才停止
```suggestion

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:54.87,0:00:57.23,Chinese,,0,0,0,,-那可不可以称您为雪花艺术家
```suggestion
Dialogue: 0,0:00:54.87,0:00:57.23,Chinese,,0,0,0,,- 那可不可以称您为雪花艺术家

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:59.95,0:01:01.52,Chinese,,0,0,0,,-我叫我雪花设计师
```suggestion
Dialogue: 0,0:00:59.95,0:01:01.52,Chinese,,0,0,0,,- 请叫我雪花设计师

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:37.56,0:01:41.66,Chinese,,0,0,0,,现在是零下13摄氏度 但我想让它延伸出主干
```suggestion
Dialogue: 0,0:01:37.56,0:01:41.66,Chinese,,0,0,0,,现在是零下13摄氏度  但我想让它长出主干

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:00.21,0:02:02.43,Chinese,,0,0,0,,那里那个小小的 那个小点
```suggestion
Dialogue: 0,0:02:00.21,0:02:02.43,Chinese,,0,0,0,,那里那个小小的  那个小点

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:46.15,0:02:48.27,Chinese,,0,0,0,,这很有意思 我可以预测未来
```suggestion
Dialogue: 0,0:02:46.15,0:02:48.27,Chinese,,0,0,0,,这很有意思  我可以预测未来

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:33.18,0:02:36.22,Chinese,,0,0,0,,-现在水汽很多 但你将看到的是枝干
```suggestion
Dialogue: 0,0:02:33.18,0:02:36.22,Chinese,,0,0,0,,- 现在水汽很多  但你将看到的是枝干

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:11.49,0:01:13.95,Chinese,,0,0,0,,我用双手来做 这就导致了雪花之间都会有些小差别
```suggestion
Dialogue: 0,0:01:11.49,0:01:13.95,Chinese,,0,0,0,,只能纯手工制作  所以雪花之间会有些小差别

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:09.04,0:01:11.49,Chinese,,0,0,0,,我不能靠一台电脑完成所有工作
```suggestion
Dialogue: 0,0:01:09.04,0:01:11.49,Chinese,,0,0,0,,然而我并没有全自动的设备

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:06.60,0:01:09.04,Chinese,,0,0,0,,因为我在设计雪花的未来
```suggestion
Dialogue: 0,0:01:06.60,0:01:09.04,Chinese,,0,0,0,,我设计这些简直就是信手拈来

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:06.98,0:00:08.61,Chinese,,0,0,0,,这太疯狂了
```suggestion
Dialogue: 0,0:00:06.98,0:00:08.61,Chinese,,0,0,0,,简直是疯了

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:34.47,0:00:36.39,Chinese,,0,0,0,,这并不和人们常常设想的一样
```suggestion
Dialogue: 0,0:00:34.47,0:00:36.39,Chinese,,0,0,0,,正常人谁能想到呢

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:43.76,0:01:46.13,Chinese,,0,0,0,,接下来我提高一点湿度
```suggestion
Dialogue: 0,0:01:43.76,0:01:46.13,Chinese,,0,0,0,,然后提高一点湿度

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:47.61,0:01:50.39,Chinese,,0,0,0,,这样你就可以看到6个主干从那里延伸出来
```suggestion
Dialogue: 0,0:01:47.61,0:01:50.39,Chinese,,0,0,0,,这样你就可以看到雪花的主干从那里延伸出来

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:56.27,0:02:00.21,Chinese,,0,0,0,,我改变了它的生长条件促进其生成主干
```suggestion
Dialogue: 0,0:01:56.27,0:02:00.21,Chinese,,0,0,0,,我改变了它的生长条件促进其生成枝干

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:02.43,0:02:05.84,Chinese,,0,0,0,,那才是唯一跟下面基柱连通的地方（这里可以注释成 “看1:19”  不然不好理解）
```suggestion
Dialogue: 0,0:02:02.43,0:02:05.84,Chinese,,0,0,0,,那才是唯一跟下面基柱连通的地方
```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:16.61,0:02:17.44,Chinese,,0,0,0,,我需要将湿度
```suggestion
Dialogue: 0,0:02:16.61,0:02:17.44,Chinese,,0,0,0,,我准备做一件事

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:17.44,0:02:19.62,Chinese,,0,0,0,,调成0
```suggestion
Dialogue: 0,0:02:17.44,0:02:19.62,Chinese,,0,0,0,,我要把湿度调成0

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:22.77,0:02:24.38,Chinese,,0,0,0,,但同样会导致雪花停止生长
```suggestion
Dialogue: 0,0:02:22.77,0:02:24.38,Chinese,,0,0,0,,但同样  雪花也会停止生长

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:42.23,0:02:44.54,Chinese,,0,0,0,,当你说 现在我要这样做
```suggestion
Dialogue: 0,0:02:42.23,0:02:44.54,Chinese,,0,0,0,,当你说  现在我要这样做  的时候

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:44.54,0:02:46.15,Chinese,,0,0,0,,然后就如你所言一样发生了
```suggestion
Dialogue: 0,0:02:44.54,0:02:46.15,Chinese,,0,0,0,,然后这事儿就发生了

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:10.68,0:02:12.02,Chinese,,0,0,0,,雪花周围这些是正在形成的水滴
```suggestion
Dialogue: 0,0:02:10.68,0:02:12.02,Chinese,,0,0,0,,这些是正在凝聚的小水滴

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:12.02,0:02:14.02,Chinese,,0,0,0,,现在我必须去除这些水滴
```suggestion
Dialogue: 0,0:02:12.02,0:02:14.02,Chinese,,0,0,0,,我超想去掉它们

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:08.20,0:02:10.68,Chinese,,0,0,0,,这会增强气流
```suggestion
Dialogue: 0,0:02:08.20,0:02:10.68,Chinese,,0,0,0,,这个可以增强气流

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:27.42,0:00:28.85,Chinese,,0,0,0,,不然人们不会买账
```suggestion
Dialogue: 0,0:00:27.42,0:00:28.85,Chinese,,0,0,0,,不然人们可不会买账

```

2021-12-07 11:52 UTC, 635f0623-fd5e-5f7f-9ce9-6b476afb90c5 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:11.34,0:00:13.53,Chinese,,0,0,0,,大概有一百纳米
```suggestion
Dialogue: 0,0:00:11.34,0:00:13.53,Chinese,,0,0,0,,大概有100纳米

```

2021-12-11 05:19 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:02.32,0:00:03.15,Chinese,,0,0,0,,-「Derek」你说什么
这里多插了一行……？

2021-12-11 06:30 UTC, ous50 requested changes

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:59.95,0:01:01.52,Chinese,,0,0,0,,-我叫我雪花设计师
Dialogue: 0,0:00:59.95,0:01:01.52,Chinese,,0,0,0,,- 我把这称为雪花设计师

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:54.87,0:00:57.23,Chinese,,0,0,0,,-那可不可以称您为雪花艺术家
Dialogue: 0,0:00:54.87,0:00:57.23,English,,0,0,0,,- 所以，您是一个雪花艺术家吗？

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:09.04,0:01:11.49,Chinese,,0,0,0,,我不能靠一台电脑完成所有工作
Dialogue: 0,0:01:09.04,0:01:11.49,Chinese,,0,0,0,,我并没有一台帮我搞定全部东西的电脑

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:11.49,0:01:13.95,Chinese,,0,0,0,,我用双手来做 这就导致了雪花之间都会有些小差别
Dialogue: 0,0:01:11.49,0:01:13.95,Chinese,,0,0,0,,我只能纯手工制作  所以雪花之间会有些小差别

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:43.76,0:01:46.13,Chinese,,0,0,0,,接下来我提高一点湿度
Dialogue: 0,0:01:43.76,0:01:46.13,Chinese,,0,0,0,,然后我要提高一点湿度

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:56.27,0:02:00.21,Chinese,,0,0,0,,我改变了它的生长条件促进其生成主干
Dialogue: 0,0:01:56.27,0:02:00.21,Chinese,,0,0,0,,我把它的生长环境调成了促进生成枝干的

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:12.02,0:02:14.02,Chinese,,0,0,0,,现在我必须去除这些水滴
Dialogue: 0,0:02:12.02,0:02:14.02,Chinese,,0,0,0,,现在我要开始去掉这些水滴了

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:12.02,0:02:14.02,Chinese,,0,0,0,,现在我必须去除这些水滴
If  something kicks into gear, it gets going or started.
https://www.usingenglish.com/reference/idioms/kick+into+gear.html

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:17.44,0:02:19.62,Chinese,,0,0,0,,调成0
Dialogue: 0,0:02:16.61,0:02:19.62,Chinese,,0,0,0,,现在我准备把湿度调成0

2021-12-11 06:30 UTC, ous50 commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:16.61,0:02:17.44,Chinese,,0,0,0,,我需要将湿度
建议将这一行去掉

2021-12-11 17:46 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:08.61,0:00:09.90,Chinese,,0,0,0,,天呐  -很疯狂 不是吗
原句的语气足够了

2021-12-11 17:48 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:39.67,0:00:42.36,Chinese,,0,0,0,,-「Derek」您真正写了一本关于雪花的著作
原句是准的

2021-12-11 17:54 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:56.27,0:02:00.21,Chinese,,0,0,0,,我改变了它的生长条件促进其生成主干
```suggestion
Dialogue: 0,0:01:56.27,0:02:00.21,Chinese,,0,0,0,,我改变了它的生长条件  促进其生成主干

```

2021-12-11 17:55 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:02.32,0:00:03.15,Chinese,,0,0,0,,-「Derek」你说什么
我觉得也可以不动

2021-12-11 18:15 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:02.32,0:00:03.15,Chinese,,0,0,0,,-「Derek」你说什么
```suggestion
Dialogue: 0,0:00:02.32,0:00:03.15,Chinese,,0,0,0,,-「Derek」你说什么？

```

2021-12-11 18:15 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:06.98,0:00:08.61,Chinese,,0,0,0,,这太疯狂了
```suggestion
Dialogue: 0,0:00:06.98,0:00:08.61,Chinese,,0,0,0,,实在是疯了

```

2021-12-11 18:25 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:47.07,0:00:50.26,Chinese,,0,0,0,,直到一本也卖不出去
```suggestion
Dialogue: 0,0:00:47.07,0:00:51.26,Chinese,,0,0,0,,直到一本也卖不出去为止

```

2021-12-11 18:25 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:22.77,0:02:24.38,Chinese,,0,0,0,,但同样会导致雪花停止生长
原句还行 不必动

2021-12-11 18:25 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:24.38,0:02:27.72,Chinese,,0,0,0,,并开始变地平整
```suggestion
Dialogue: 0,0:02:24.38,0:02:27.72,Chinese,,0,0,0,,并开始变得平整

```

2021-12-11 18:28 UTC, ksyx reviewed
- branch 称作主干真的合适吗
- 适当调整语序

thx

2021-12-11 18:28 UTC, ksyx commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:06.60,0:01:09.04,Chinese,,0,0,0,,因为我在设计雪花的未来
```suggestion
Dialogue: 0,0:01:06.60,0:01:09.04,Chinese,,0,0,0,,因为我同时在设计它们

```

2021-12-11 18:28 UTC, ksyx commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:01:43.76,0:01:46.13,Chinese,,0,0,0,,接下来我提高一点湿度
```suggestion
Dialogue: 0,0:01:43.76,0:01:46.13,Chinese,,0,0,0,,现在我把湿度提高一点
```

2021-12-11 18:28 UTC, ksyx commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:44.54,0:02:46.15,Chinese,,0,0,0,,然后它就发生了
当你说什么它就怎么变的时候
你就真的觉得你开始了解它了

2021-12-11 18:28 UTC, ksyx commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:46.15,0:02:48.27,Chinese,,0,0,0,,这很有意思  我可以预测未来
```suggestion
Dialogue: 0,0:02:46.15,0:02:48.27,Chinese,,0,0,0,,我可以预测未来  这很有意思
```

2021-12-11 18:31 UTC, H3arn commented on snowflakes/snowflakes.ass
>  Dialogue: 0,0:00:47.07,0:00:50.26,English,,0,0,0,,until finally  they sold zero copies,
太长

2021-12-11 18:31 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:16.61,0:02:17.44,Chinese,,0,0,0,,我需要将湿度
```suggestion
Dialogue: 0,0:02:16.61,0:02:17.44,Chinese,,0,0,0,, 

```

2021-12-11 18:40 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:21.93,0:00:25.55,Chinese,,0,0,0,,生成雪花的指尖魔法是存在的
原句蛮浪漫的 可以不动（

2021-12-11 18:40 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:39.67,0:00:42.36,Chinese,,0,0,0,,-「Derek」您真正写了一本关于雪花的著作
literally 留着或许更好

2021-12-11 18:40 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:42.23,0:02:44.54,Chinese,,0,0,0,,当你说  现在我要这样做  的时候
```suggestion
Dialogue: 0,0:02:42.23,0:02:44.54,Chinese,,0,0,0,,只要你说  现在我要这样做 
```

2021-12-11 18:40 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:39.98,0:02:42.23,Chinese,,0,0,0,,你真的开始觉得你明白发生了什么
```suggestion
Dialogue: 0,0:02:39.98,0:02:42.23,Chinese,,0,0,0,,你真的觉得 你开始了解它了
```

2021-12-11 18:40 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:44.54,0:02:46.15,Chinese,,0,0,0,,然后它就发生了
```suggestion
Dialogue: 0,0:02:44.54,0:02:46.15,Chinese,,0,0,0,,然后它就成真了

```

2021-12-13 00:20 UTC, ksyx commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:39.67,0:00:42.36,Chinese,,0,0,0,,-「Derek」您真正写了一本关于雪花的著作
很怪啊 真正写了一本书

2021-12-13 09:25 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:08.61,0:00:09.90,Chinese,,0,0,0,,天呐  -很疯狂 不是吗
```suggestion
Dialogue: 0,0:00:08.61,0:00:09.90,Chinese,,0,0,0,,天呐  - 很疯狂 不是吗

```

2021-12-13 09:25 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:15.76,0:00:19.00,Chinese,,0,0,0,,Ken Libbrecht博士是一位雪花狂人
```suggestion
Dialogue: 0,0:00:15.76,0:00:19.00,Chinese,,0,0,0,,Ken Libbrecht 博士是一位雪花狂人

```

2021-12-13 09:25 UTC, H3arn commented on snowflakes/snowflakes.ass
>  Dialogue: 0,0:00:47.07,0:00:50.26,English,,0,0,0,,until finally  they sold zero copies,
```suggestion
Dialogue: 0,0:00:47.07,0:00:50.26,English,,0,0,0,,until finally they sold zero copies,

```

2021-12-13 09:37 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:02:44.54,0:02:46.15,Chinese,,0,0,0,,然后它就发生了
```suggestion
Dialogue: 0,0:02:44.54,0:02:46.15,Chinese,,0,0,0,,然后它就实现了

```

2021-12-13 09:44 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:42.36,0:00:45.04,Chinese,,0,0,0,,-我曾连续写出两本成功的书
这边成功的标准是热销嘛...
看下文的话似乎算是

2021-12-13 09:47 UTC, H3arn commented on snowflakes/snowflakes.ass
> +Dialogue: 0,0:00:42.36,0:00:45.04,Chinese,,0,0,0,,- 我曾经连续写出两本成功的书
@ksyx I will apply your suggestion here.
The original one seemed outdated, sorry.

```suggestion
Dialogue: 0,0:00:42.36,0:00:45.04,Chinese,,0,0,0,,- 我曾连续写出两本热销书

```

2021-12-13 09:48 UTC, merged